upstream client_app_backend {
    # Round-Robin Load Balancing across all 3 C# Backends
    server main.capstone.com:5000;
    server annex.capstone.com:5000;
    server pubad.capstone.com:5000;
}

upstream middleware_backend {
    # Round-Robin Load Balancing across all 3 Node.js Backends
    server main.capstone.com:4000;
    server annex.capstone.com:4000;
    server pubad.capstone.com:4000;
}

server {
    listen 80;
    server_name localhost;

    location /api/Auth/ {
        proxy_pass http://client_app_backend;
    }

    location /api/ {
        proxy_pass http://middleware_backend;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}