---
# Secrets for plv-fabric
apiVersion: v1
kind: Secret
metadata:
  name: blockgo-secrets
  namespace: plv-fabric
type: Opaque
stringData:
  JWT_SECRET: "32h//crQb+CfYGjR9JhllVl02sa9ByCiX044Tb2M9wU="
  INTERNAL_API_KEY: "de70901b71a67b0b064e478771fa49fd47611422dbe8f9f4ee99b5075dcef008"
  WALLET_ENCRYPTION_KEY: "3751d27a85b727ec0c7b9f3286fa08fac7b1e76c9259d3509bc83c3e3cc99bc3"
  IPFS_ENCRYPTION_KEY: "3751d27a85b727ec0c7b9f3286fa08fa"
  POSTGRES_USER: "BLOCKGO"
  POSTGRES_PASS: "PLVBLOCKGO"
  POSTGRES_DB: "ActivityLogs"
  POSTGRES_REPL_PASS: "replica_pass_123"
  COUCHDB_USER: "capstone"
  COUCHDB_PASS: "pass123"
  BOOTSTRAP_REGISTRAR_PASS: "admin123"
  CHAINCODE_ID_REGISTRAR: "registrar_1.0:cb8fbbc0a8f1e7bd04378ef5411c86370c5c5d96be7c44cbe2c533ccf5dcf103"
  CHAINCODE_ID_FACULTY: "registrar_1.0:8db9aa5909dbd7b6e6f4be2ff639f15a8d097eda65c7688bd02149cd5d3c2fb8"
  CHAINCODE_ID_DEPARTMENT: "registrar_1.0:c88c47f1bd5d5c1d4786d3ff1816eef3e8b25e9c21df7e3c80b26a4206884a9d"
  FABRIC_CA_REGISTRAR_PASS: "admin123"
  FABRIC_CA_FACULTY_PASS: "admin123"
  FABRIC_CA_DEPARTMENT_PASS: "admin123"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USER: "plv.registrar.blockgo@gmail.com"
  EMAIL_PASS: "wrqszerfchfxxcrm"
  EMAIL_FROM: "PLV Registrar <noreply@capstone.com>"
---
# Secrets for plv-main-campus
apiVersion: v1
kind: Secret
metadata:
  name: blockgo-secrets
  namespace: plv-main-campus
type: Opaque
stringData:
  POSTGRES_USER: "BLOCKGO"
  POSTGRES_PASS: "PLVBLOCKGO"
  POSTGRES_DB: "ActivityLogs"
  POSTGRES_REPL_PASS: "replica_pass_123"
  COUCHDB_USER: "capstone"
  COUCHDB_PASS: "pass123"
  BOOTSTRAP_REGISTRAR_PASS: "admin123"
  CHAINCODE_ID_REGISTRAR: "registrar_1.0:cb8fbbc0a8f1e7bd04378ef5411c86370c5c5d96be7c44cbe2c533ccf5dcf103"
  CHAINCODE_ID_FACULTY: "registrar_1.0:8db9aa5909dbd7b6e6f4be2ff639f15a8d097eda65c7688bd02149cd5d3c2fb8"
  CHAINCODE_ID_DEPARTMENT: "registrar_1.0:c88c47f1bd5d5c1d4786d3ff1816eef3e8b25e9c21df7e3c80b26a4206884a9d"
---
# Secrets for plv-annex-campus
apiVersion: v1
kind: Secret
metadata:
  name: blockgo-secrets
  namespace: plv-annex-campus
type: Opaque
stringData:
  POSTGRES_USER: "BLOCKGO"
  POSTGRES_PASS: "PLVBLOCKGO"
  POSTGRES_DB: "ActivityLogs"
  POSTGRES_REPL_PASS: "replica_pass_123"
  COUCHDB_USER: "capstone"
  COUCHDB_PASS: "pass123"
  BOOTSTRAP_REGISTRAR_PASS: "admin123"
  CHAINCODE_ID_REGISTRAR: "registrar_1.0:cb8fbbc0a8f1e7bd04378ef5411c86370c5c5d96be7c44cbe2c533ccf5dcf103"
  CHAINCODE_ID_FACULTY: "registrar_1.0:8db9aa5909dbd7b6e6f4be2ff639f15a8d097eda65c7688bd02149cd5d3c2fb8"
  CHAINCODE_ID_DEPARTMENT: "registrar_1.0:c88c47f1bd5d5c1d4786d3ff1816eef3e8b25e9c21df7e3c80b26a4206884a9d"
---
# Secrets for plv-pubad-campus
apiVersion: v1
kind: Secret
metadata:
  name: blockgo-secrets
  namespace: plv-pubad-campus
type: Opaque
stringData:
  POSTGRES_USER: "BLOCKGO"
  POSTGRES_PASS: "PLVBLOCKGO"
  POSTGRES_DB: "ActivityLogs"
  POSTGRES_REPL_PASS: "replica_pass_123"
  COUCHDB_USER: "capstone"
  COUCHDB_PASS: "pass123"
  BOOTSTRAP_REGISTRAR_PASS: "admin123"
  CHAINCODE_ID_REGISTRAR: "registrar_1.0:cb8fbbc0a8f1e7bd04378ef5411c86370c5c5d96be7c44cbe2c533ccf5dcf103"
  CHAINCODE_ID_FACULTY: "registrar_1.0:8db9aa5909dbd7b6e6f4be2ff639f15a8d097eda65c7688bd02149cd5d3c2fb8"
  CHAINCODE_ID_DEPARTMENT: "registrar_1.0:c88c47f1bd5d5c1d4786d3ff1816eef3e8b25e9c21df7e3c80b26a4206884a9d"
---
# Config for plv-fabric
apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-config
  namespace: plv-fabric
data:
  CHANNEL_NAME: "registrar-channel"
  CHAINCODE_NAME: "registrar"
  FABRIC_CFG_PATH: "/etc/hyperledger/fabric"
  FABRIC_LOGGING_SPEC: "INFO"
---
# Config for plv-main-campus (Orderer & Peer)
apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-config
  namespace: plv-main-campus
data:
  CHANNEL_NAME: "registrar-channel"
  CHAINCODE_NAME: "registrar"
  FABRIC_CFG_PATH: "/etc/hyperledger/fabric"
  FABRIC_LOGGING_SPEC: "INFO"
  ORDERER_GENERAL_TLS_ENABLED: "true"
  ORDERER_GENERAL_LISTENADDRESS: "0.0.0.0"
  ORDERER_GENERAL_GENESISMETHOD: "file"
  ORDERER_GENERAL_GENESISFILE: "/var/hyperledger/orderer/orderer.genesis.block"
  ORDERER_GENERAL_TLS_PRIVATEKEY: "/var/hyperledger/orderer/tls/server.key"
  ORDERER_GENERAL_TLS_CERTIFICATE: "/var/hyperledger/orderer/tls/server.crt"
  ORDERER_GENERAL_TLS_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: "/var/hyperledger/orderer/tls/server.crt"
  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: "/var/hyperledger/orderer/tls/server.key"
  ORDERER_GENERAL_CLUSTER_ROOTCAS: "[/var/hyperledger/orderer/tls/ca.crt]"
  ORDERER_GENERAL_METRICS_PROVIDER: "prometheus"
---
# Config for plv-main-campus (Postgres)
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: plv-main-campus
data:
  POSTGRES_DB: "ActivityLogs"
  POSTGRES_INITDB_ARGS: "-c shared_preload_libraries=pg_stat_statements"
---
# IPFS Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-config
  namespace: plv-fabric
data:
  server.json: |
    {
      "API": "/ip4/0.0.0.0/tcp/5001",
      "Gateway": "/ip4/0.0.0.0/tcp/8080",
      "Addresses": {
        "Swarm": ["/ip4/0.0.0.0/tcp/4001", "/ip6/::/tcp/4001"]
      }
    }
