---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: blockgo-managed-cert
  namespace: plv-fabric
spec:
  domains:
    - plv-blockgo.com
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: blockgo-frontend-config
  namespace: plv-fabric
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: plv-fabric
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "blockgo-managed-cert"
    networking.gke.io/v1beta1.FrontendConfig: "blockgo-frontend-config"
spec:
  rules:
  - host: plv-blockgo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80