Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: ../crypto-config-final-v2/ordererOrganizations/capstone.com/msp
    Policies:
      Readers: { Type: Signature, Rule: "OR('OrdererMSP.member')" }
      Writers: { Type: Signature, Rule: "OR('OrdererMSP.member')" }
      Admins: { Type: Signature, Rule: "OR('OrdererMSP.admin')" }
    OrdererEndpoints:
      - orderer.capstone.com:7050
      - orderer2.capstone.com:8050
      - orderer3.capstone.com:9050

  - &RegistrarOrg
    Name: RegistrarMSP
    ID: RegistrarMSP
    MSPDir: ../crypto-config-final-v2/peerOrganizations/registrar.capstone.com/msp
    Policies:
      Readers: { Type: Signature, Rule: "OR('RegistrarMSP.admin', 'RegistrarMSP.peer', 'RegistrarMSP.client')" }
      Writers: { Type: Signature, Rule: "OR('RegistrarMSP.admin', 'RegistrarMSP.client')" }
      Admins: { Type: Signature, Rule: "OR('RegistrarMSP.admin')" }
      Endorsement: { Type: Signature, Rule: "OR('RegistrarMSP.peer')" }
    AnchorPeers:
      - Host: peer0.registrar.capstone.com
        Port: 7051

  - &FacultyOrg
    Name: FacultyMSP
    ID: FacultyMSP
    MSPDir: ../crypto-config-final-v2/peerOrganizations/faculty.capstone.com/msp
    Policies:
      Readers: { Type: Signature, Rule: "OR('FacultyMSP.admin', 'FacultyMSP.peer', 'FacultyMSP.client')" }
      Writers: { Type: Signature, Rule: "OR('FacultyMSP.admin', 'FacultyMSP.client')" }
      Admins: { Type: Signature, Rule: "OR('FacultyMSP.admin')" }
      Endorsement: { Type: Signature, Rule: "OR('FacultyMSP.peer')" }
    AnchorPeers:
      - Host: peer0.faculty.capstone.com
        Port: 7051

  - &DepartmentOrg
    Name: DepartmentMSP
    ID: DepartmentMSP
    MSPDir: ../crypto-config-final-v2/peerOrganizations/department.capstone.com/msp
    Policies:
      Readers: { Type: Signature, Rule: "OR('DepartmentMSP.admin', 'DepartmentMSP.peer', 'DepartmentMSP.client')" }
      Writers: { Type: Signature, Rule: "OR('DepartmentMSP.admin', 'DepartmentMSP.client')" }
      Admins: { Type: Signature, Rule: "OR('DepartmentMSP.admin')" }
      Endorsement: { Type: Signature, Rule: "OR('DepartmentMSP.peer')" }
    AnchorPeers:
      - Host: peer0.department.capstone.com
        Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Channel: &ChannelDefaults
  Policies:
    Readers: { Type: ImplicitMeta, Rule: "ANY Readers" }
    Writers: { Type: ImplicitMeta, Rule: "ANY Writers" }
    Admins: { Type: ImplicitMeta, Rule: "MAJORITY Admins" }
  Capabilities:
    <<: *ChannelCapabilities

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers: { Type: ImplicitMeta, Rule: "ANY Readers" }
    Writers: { Type: ImplicitMeta, Rule: "ANY Writers" }
    Admins: { Type: ImplicitMeta, Rule: "MAJORITY Admins" }
    LifecycleEndorsement: { Type: ImplicitMeta, Rule: "MAJORITY Endorsement" }
    Endorsement: { Type: ImplicitMeta, Rule: "MAJORITY Endorsement" }
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
            - Host: orderer.capstone.com
              Port: 7050
              ClientTLSCert: /etc/hyperledger/fabric/crypto-config-final-v2/ordererOrganizations/capstone.com/orderers/orderer.capstone.com/tls/server.crt
              ServerTLSCert: /etc/hyperledger/fabric/crypto-config-final-v2/ordererOrganizations/capstone.com/orderers/orderer.capstone.com/tls/server.crt
            - Host: orderer2.capstone.com
              Port: 8050
              ClientTLSCert: /etc/hyperledger/fabric/crypto-config-final-v2/ordererOrganizations/capstone.com/orderers/orderer2.capstone.com/tls/server.crt
              ServerTLSCert: /etc/hyperledger/fabric/crypto-config-final-v2/ordererOrganizations/capstone.com/orderers/orderer2.capstone.com/tls/server.crt
            - Host: orderer3.capstone.com
              Port: 9050
              ClientTLSCert: /etc/hyperledger/fabric/crypto-config-final-v2/ordererOrganizations/capstone.com/orderers/orderer3.capstone.com/tls/server.crt
              ServerTLSCert: /etc/hyperledger/fabric/crypto-config-final-v2/ordererOrganizations/capstone.com/orderers/orderer3.capstone.com/tls/server.crt
    Addresses:
        - orderer.capstone.com:7050
        - orderer2.capstone.com:8050
        - orderer3.capstone.com:9050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers: { Type: ImplicitMeta, Rule: "ANY Readers" }
        Writers: { Type: ImplicitMeta, Rule: "ANY Writers" }
        Admins: { Type: ImplicitMeta, Rule: "MAJORITY Admins" }
        BlockValidation: { Type: ImplicitMeta, Rule: "ANY Writers" }

Profiles:
  UniversityGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      UniversityConsortium:
        Organizations:
          - *RegistrarOrg
          - *FacultyOrg
          - *DepartmentOrg

  RegistrarChannel:
    Consortium: UniversityConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *RegistrarOrg
        - *FacultyOrg
        - *DepartmentOrg
    Capabilities:
        <<: *ApplicationCapabilities